apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payroll
    department: finance
    tier: backend
    env: dev
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payroll
      department: finance
      tier: backend
      env: dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payroll
        department: finance
        tier: backend
        env: dev
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
        - sleep
        - "4800"
        resources: {}
status: {}
