apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payroll
    department: finance
    tier: frontend
    env: prod
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll
      department: finance
      tier: frontend
      env: prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payroll
        department: finance
        tier: frontend
        env: prod
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
