apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-01-31T12:28:38Z"
  generation: 2
  labels:
    run: nginx-deploy
  name: nginx-deploy
  namespace: default
  resourceVersion: "871840"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx-deploy
  uid: 3505cc31-4425-11ea-85ee-0242ac11000b
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx-deploy
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: Always
        name: nginx-deploy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: com.docker.ucp.manager
        operator: Exists
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-01-31T12:34:19Z"
    lastUpdateTime: "2020-01-31T12:34:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-01-31T12:28:38Z"
    lastUpdateTime: "2020-01-31T12:40:47Z"
    message: ReplicaSet "nginx-deploy-6bcfcb96fd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
