apiVersion: v1
kind: Pod
metadata:
  name: fast-pod
spec:
  containers:
  - args:
    - sleep
    - "1000"
    image: ubuntu
    imagePullPolicy: Always
    name: cpu-stress
    resources:
      limits:
        cpu: 2
      requests:
        cpu: 1
