apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: large-deployment
  name: large-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      run: large-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: large-deployment
    spec:
      containers:
      - image: nginx
        name: large-deployment
        resources: {}
status: {}
