apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: master-deployment
  name: master-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      run: master-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: master-deployment
    spec:
      containers:
      - image: busybox
        name: master-deployment
        command: ["sleep", "4800"]
        resources: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
status: {}
