apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-2
  name: webapp-2
spec:
  containers:
  - env:
    - name: OVERRIDE_USER
      value: USER30
    image: kodekloud/event-simulator
    imagePullPolicy: Always
    name: simple-webapp
  - command:
    - sleep
    - "5000"
    image: busybox
    imagePullPolicy: Always
    name: db
